language: python
python: "3.7"
dist: bionic
env:
  global:
    - ENV = test
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: python -m pytest test/unit
